version: "3.8"

services:
  php:
    build: ./php-app
    container_name: php-container
    ports:
      - "8081:8081"
    networks:
      - app-network

  java:
    build: ./java-app
    container_name: java-container
    networks:
      - app-network

  node:
    build: ./node-app
    container_name: node-container
    ports:
      - "8082:8082"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
