version: "3.8"

services:
  load-balancer:
    image: nginx:latest
    container_name: nginx-lb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"  # Exponiendo el puerto 80 para acceder a través de HTTP
    networks:
      - app-network

  php:
    build: ./php-app
    container_name: php-container
    ports:
      - "8081:8081"
    networks:
      - app-network

  java:
    build: ./java-app
    container_name: java-container
    ports:
      - "8080:8080"
    networks:
      - app-network

  node:
    build: ./node-app
    container_name: node-container
    ports:
      - "8082:8082"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
